# -*- coding: utf-8 -*-
"""Class 22- File Handling in Python-CipherSchools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6BSPd-52FguCEkhiK7BjoWDmk30ct8k
"""

file=open("random.txt",'w')

file.write("blah blah blah")

file.write("\n new line")

file.close()

file=open("random.txt",'w')

file.write("meehir lokhande")

a=["meehir","mayank","tanishq","tanmay"]

file.writelines(a)



file=open("sample.txt","r")

file.read()

print(file.read())

with open("random.txt","r") as file:
  print(file.read())
print(file.read())

class A:
  def __enter__(self):
    print("Entered")
    return 1
  def __exit__(self,*args):
    print("Exitted")
    print(args)
    return True

with A() as x:
  print(x)
  print("inside context")
  raise Exception 
print("outside context")

''''
<html>
    <body>
        hello world
    </body>
</html>
'''

'''jason
{
    "html": {
        "body": "Hello World"
    }
}
'''

a = {
    "name": "meehir lokhande",
     "marks" : 100,
     "languages": [
         "python"
         "html"
         "css"
         "java script"
     ]
}

import json

json.dumps(a)

